---
openapi: 3.0.1
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: show user
      tags:
      - User
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: errors
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
                  - first_name
                  - last_name
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
